movieproject/movieapp/urls.py
from django.urls import path
from .import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static (settings.STATIC_URL,
                           document_root=settings.STATIC_ROOT)
    urlpatterns += static (settings.MEDIA_URL,
                           document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')



def __str__(self):
    return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movies
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movies
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movies
from .forms import MovieForm


# Create your views here.



def index(request):
    movie=Movies.objects.all()
    context={'movie_list':movie}
    return render(request,'index.html',context)
def details(request,movie_id):
    movie=Movies.objects.get(id=movie_id)
    return render(request,'details.html',{'movie':movie})
def add(request):
    if request.method =='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('description',)
        year=request.POST.get('year',)
        image=request.FILES['img']
        movie=Movies(name=name,desc=desc,year=year,img=image)
        movie.save()
    return render(request,'add.html')
def update(request,id):
    movie=Movies.objects.get(id=id)
    form=MovieForm(request.POST or None ,request.FILES ,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'movie':movie,'form':form})
def delete(request,id):
    if request.method=='POST':
        movie=Movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
  <input type="text" name="name" placeholder= "enter movie name"><br>
  <input type="text" name="description" placeholder= "enter movie description"><br>
  <input type="text" name="year" placeholder= "enter movie year"><br>

   <div>
    <input type="file" name="img" ><br>
    <button type="submit">Sumbit</button>
   </div>





</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    ONLINE MOVIE STORE
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  Are you sure,you want to delete this movie?<br>
  <button class="btn btn-primary" type="submit">DELETE</button>
</form>
{% endblock %}

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">

            <img src="{{movie.img.url}}" width="380" height="500">

        </div>
        <div class="col-md-3">
           <h2> {{movie.name}}</h2>
           <h6>{{movie.desc}}</h6>

           <h4> {{movie.year}}</h4>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>



        </div>




    </div>



</div>




{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}

  <button type="submit" class="btn btn-secondary">Submit</button>


</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<a class="btn btn-info" href="{% url 'movieapp:add'%}">Add movie</a>

<div class="container">

    <div class="row">
        {% for i in movie_list %}
         <div class="col-md-3">
             <div class="card" >
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.year}}</p>
    <a href="{% url 'movieapp:details' i.id%}" class="btn btn-warning">Movie Details</a>
  </div>
</div>



        </div>

{% endfor %}
    </div>

</div>







{% endblock %}