shopproject/cart/urls.py
from django.urls import path
from .import views

app_name='cart'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')


]

shopproject/searchapp/urls.py
from django.urls import path
from .import views
app_name='searchapp'

urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

shopproject/shopapp/urls.py
from django.urls import path
from . import views
app_name='shopapp'
urlpatterns=[
    path('',views.allProductCategory,name='allproducts'),
    path('<slug:c_slug>/',views.allProductCategory,name='product-by-category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.productDetails,name='productdetail')
]

shopproject/shopproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shopapp.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static (settings.STATIC_URL,
                           document_root=settings.STATIC_ROOT)
    urlpatterns += static (settings.MEDIA_URL,
                           document_root=settings.MEDIA_ROOT)

shopproject/cart/models.py
from django.db import models
from shopapp.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=20,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering =['date_added']
    def __str__(self):
        return '{}' .format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}' .format(self.product)

shopproject/searchapp/models.py
from django.db import models

# Create your models here.

shopproject/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural ='categories'
    def get_url(self):
        return reverse('shopapp:product-by-category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shopapp:productdetail',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

shopproject/cart/views.py
from django.shortcuts import render, redirect,get_object_or_404
from shopapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def cart_Id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cart_Id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=cart_Id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item .save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cart_Id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
      cart=Cart.objects.get(cart_id=cart_Id(request))
      product= get_object_or_404(Product,id=product_id)
      cart_item=CartItem.objects.get(product=product,cart=cart)
      if cart_item.quantity > 1:
         cart_item.quantity -= 1
         cart_item.save()
      else:
         cart_item.delete()
      return  redirect('cart:cart_detail')
def full_remove(request,product_id):
      cart = Cart.objects.get(cart_id=cart_Id(request))
      product = get_object_or_404(Product, id=product_id)
      cart_item = CartItem.objects.get(product=product, cart=cart)
      cart_item.delete()
      return redirect('cart:cart_detail')

shopproject/searchapp/views.py
from django.shortcuts import render
from django.db.models import Q
from shopapp.models import Product
# Create your views here.
def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query= request.GET.get('q')
        products= Product.objects.all().filter(Q(name__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

shopproject/shopapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.

# def index(request):
#     return  HttpResponse('welcome')
def allProductCategory(request,c_slug=None):
    c_page= None
    products_list= None
    if c_slug != None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'products':products})
def productDetails(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
            raise e
    return render(request,'product.html',{'product':product})

shopproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js" ></script>


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

<div class="container" >
<div>

    {% include 'header.html' %}

    {% include 'navbar.html' %}
    <br>

    {% block content %}

    {% endblock %}

<br>
</div>

{% include 'footer.html' %}
<!--    <script src="{% static 'js/jquery.slim.min.js' %}"></script>-->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>

</div>
</body>
</html>

shopproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
Review your cart items and place your order.
{% endblock %}

{% block title %}
Cart
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Cart Is Empty
        </h1>
        <br>
        <p> Please click <a href="{% url 'shopapp:allproducts' %}">HERE</a> to continue shopping</p>
    </div>
</div>
{% else %}
<div>
<div class="text-center">
    <br>
         <h1 class="text-center my_cart_title">***Your Shopping Cart***</h1>
    <br>
</div>
    <div class="row mx_auto">
        <div class="col12 col-sm-12 col-md-12 col-lg-6 text-center">
          <table class=" table my_custom_table">
                <thead class="my_table_head">
                    <tr>
                        <th colspan="5">
                               Your Cart Items
                        </th>
                    </tr>
                </thead>
              <br>
              <br>
              <tbody>
                {% for cart_item in cart_items %}
              <tr>
                    <td>
                    <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" alt=""  width="140px;" height="130px;"; class="float-left rounded custom_image"></a>
                    </td>
                  <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    price:$ {{cart_item.product.price}}
                    <br>
                    QTY: {{cart_item.quantity}} x {{cart_item}}
                  </td>
                  <td>
                    $ {{cart_item.sub_total}}
                  </td>
                  {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                      <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus-square custom_icon"></i></a>
                    &nbsp;&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus-square custom_icon"></i></a>
                    &nbsp;&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon" ></i></a>
                    </td>
                  {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus-square custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon" ></i></a>
                    </td>
                  {% endif %}
              </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="col12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_table_head">
                <tr>
                    <th>
                         Check Out
                    </th>
                </tr>
                </thead>
                <br>
                <br>
                <tbody>
                <tr>
                    <td>
                        Please review your cart items before proceeding with order payment
                    </td>
                </tr>
                </tbody>
            </table>
            <br>
            <div>
                <div>
                 <a href="{% url 'shopapp:allproducts' %}"><button class="btn btn-warning  custom_button"> continue shopping</button></a>
                </div>
            </div>
            {% endif %}
        </div>

</div>
</div>



{% endblock %}

shopproject/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        Welcome to ABC-Fashion Store where you can find your styles....moving with trends!!!!!
    {% endif %}
{% endblock %}
<br>

{% block title %}
    {% if category %}
        {{category.name}} -- ABC -Fashion Store
    {% else %}
        our new and trendy collections brings out fashion in you *****
    {% endif %}
{% endblock %}

<br>

{% block content %}

{% if category %}
    <div classs="row my_row_class">
      <div class="mx_auto">
        <p> <a href="{% url 'shopapp:allproducts' %}"> our new Products </a>
        </p>
      </div>
         </div>
        {% endif %}
        <div>
            {% if category %}
                <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">

        </div>
        <br>
         <div>
                <h1 class="text-center my_title"> {{category.name}}</h1>
        </div>

        <div>
                <p class="text-justify">{{category.description}}</p>
        </div>
            {% else %}

<div>
    <div>
        <img  class="my_image  my_image_padding" src="{% static 'img/banner.png' %}" alt="ABC-Fashion Store finds your style" ;>
    </div><br>
    <div>
        <h1 class="text-center my_title">Our new collections</h1>
        <p class="text-justify">You might already be familiar with fashion-forward contemporary brands like Ganni, Staud, and Nanushka—but a new class of minimal, neutral palette–loving labels has emerged. From LVIR to Loulou Studio to Totême, a mix of up-and-coming and well-established labels are finding success within the more approachable and price-conscious space they occupy in the contemporary category of the womenswear market. Their devotees are style-conscious individuals who don’t want to compromise on taste, prefer slow to fast fashion, and gravitate toward minimalism.</p>
    </div>
        {% endif %}

</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem">
                <a href="{{product.get_url}}"><img  width="1700px;" height="230px;" class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}"></a>
            </div>
            <div class="card-body">
                <h4 class="text-center">{{product.name}}</h4>
                 <p class="text-center">{{product.price}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
        {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-dark btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

shopproject/templates/footer.html
<div class="footer  navbar-fixed-bottom  my_footer">
 <p class="text-center"> © Copyright 2023 ABC-Store.blog. All rights reserved.Following the new trends...</p>

</div>

shopproject/templates/header.html
{% load static %}
<header>

 <center>
   <a href="{% url 'shopapp:allproducts' %}"/> <img  src="{% static 'img/logo.png' %}" alt="logo image" width="240px;" height="230px;">
</center>


</header>

shopproject/templates/navbar.html
<nav class=" navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}" >
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu"aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shopapp:allproducts' %}">New Collections</a>
          <a class="dropdown-item" href="{% url 'shopapp:allproducts' %}">All products</a>
          <div class="dropdown-divider"></div>
            {% for cat in links %}
          <a class="dropdown-item" href="{{ cat.get_url }}">{{cat.name}}</a>
            {% endfor %}
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart" ></i>{{item_count}}</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0"  action="{% url 'searchapp:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search" ></i></button>
    </form>
  </div>
</nav>

shopproject/templates/product.html
{% extends 'base.html' %}
{% load static %}


{% block metadescription %}
{{product.description|truncatewords:155}}
Welcome to ABC-Fashion world***
{% endblock %}

{% block title %}
{% if category %}
{{product.name}}
{% endif %}
{% endblock %}

{% block content %}
<div class="my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shopapp:allproducts' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}} </p>
    </div>
</div>

<div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center ">
            <div style="min-width:18rem">
            <img  class="my_prod_image" src="{{product.image.url}}" alt="{{product.name}}">
            </div>
        </div>

    <div class="col-12 col-sm-12 col-md-6 col-lg-6 text-center ">

            <h1 class=" text-center my_prod_title">{{product.name}}</h1>
            <div>
                <p class="prod_price">${{product.price}}</p>
            </div>
            <div>
                <p style="text-align:left;font-weight:bold;"> Product Description:</p>
                <p class="text-justify my_prod_text">{{product.description}}</p>
            </div>
            {% if product.stock <= 0 %}
            <p class="my_prod_text"><b>Out of Stock</b></p>
            {% else %}
            <a  class="btn btn-info" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}

    </div>
    </div>
</div>





{% endblock %}

shopproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
continue shopping to purchase your favorites
{% endblock %}

{% block title %}
Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_title"> You have searched for: <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem">
                <a href="{{product.get_url}}"><img  width="1700px;" height="230px;" class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}"></a>
            </div>
            <div class="card-body">
                <h4 class="text-center">{{product.name}}</h4>
                 <p class="text-center">{{product.price}}</p>
            </div>
        </div>
        {% empty %}
        <div class=" text-center row mx_auto">
            <p class="text-center my_search_title"> <b> 0 </b>Results Found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}